# Generated by Django 5.0.6 on 2024-05-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_novedad_novedadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='EmpleadoID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='NominaID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='NovedadID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
