# Generated by Django 5.0.5 on 2024-05-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAutor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreGenero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreGenero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('AnioPublicacion', models.IntegerField()),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('AnioLanzamiento', models.IntegerField()),
                ('Duracion', models.TimeField()),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.autor')),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.libro')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='Libros',
            field=models.ManyToManyField(through='productos.LibroAutor', to='productos.libro'),
        ),
        migrations.CreateModel(
            name='LibroGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneroLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.generolibro')),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.libro')),
            ],
        ),
        migrations.AddField(
            model_name='generolibro',
            name='Libros',
            field=models.ManyToManyField(through='productos.LibroGenero', to='productos.libro'),
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneroPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.generopelicula')),
                ('Pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='generopelicula',
            name='Peliculas',
            field=models.ManyToManyField(through='productos.PeliculaGenero', to='productos.pelicula'),
        ),
    ]
