# Generated by Django 5.0.6 on 2024-05-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=17, null=True)),
                ('codigo_idioma', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_publicacion', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('promedio_calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cantidad_calificaciones', models.IntegerField(blank=True, null=True)),
                ('cantidad_resenas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_lanzamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.generopelicula')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='AutorLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.libro')),
            ],
            options={
                'unique_together': {('libro', 'autor')},
            },
        ),
    ]
