# Generated by Django 5.0.5 on 2024-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='NombreAutor',
            new_name='nombre_autor',
        ),
        migrations.RenameField(
            model_name='generolibro',
            old_name='NombreGenero',
            new_name='nombre_genero',
        ),
        migrations.RenameField(
            model_name='generopelicula',
            old_name='NombreGenero',
            new_name='nombre_genero',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='AnioPublicacion',
            new_name='anio_publicacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='Calificacion',
            new_name='calificacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='libroautor',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='libroautor',
            old_name='Libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='librogenero',
            old_name='GeneroLibro',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='librogenero',
            old_name='Libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='AnioLanzamiento',
            new_name='anio_lanzamiento',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='peliculagenero',
            old_name='GeneroPelicula',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='peliculagenero',
            old_name='Pelicula',
            new_name='pelicula',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='Libros',
        ),
        migrations.RemoveField(
            model_name='generolibro',
            name='Libros',
        ),
        migrations.RemoveField(
            model_name='generopelicula',
            name='Peliculas',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='Calificacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='Duracion',
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(through='productos.LibroAutor', to='productos.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_calificaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_resenas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='codigo_idioma',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(through='productos.LibroGenero', to='productos.generolibro'),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn13',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='libroautor',
            unique_together={('libro', 'autor')},
        ),
        migrations.AlterUniqueTogether(
            name='librogenero',
            unique_together={('libro', 'genero')},
        ),
        migrations.AlterUniqueTogether(
            name='peliculagenero',
            unique_together={('pelicula', 'genero')},
        ),
    ]
