# Generated by Django 5.0.5 on 2024-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_nombreautor_autor_nombre_autor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peliculagenero',
            unique_together=set(),
        ),
    ]
